export {
  type OfficeBridgeClientOptions,
  type OfficeBridgeConnectionDetails,
  type OfficeBridgeConnectionPhase,
  type OfficeBridgeConnectionStatus,
  type OfficeBridgeController,
  type OfficeBridgeInvokeTimeoutDetails,
  type OfficeBridgeSessionHealth,
  startOfficeBridge,
} from "./client.js";
export { DOM_QUERIES } from "./dom-queries.js";
export {
  bridgeToolExecutionResultToMcpResult,
  createOfficeBridgeMcpServer,
  describeBridgeConnectionFailure,
  describeMissingBridgeSession,
} from "./mcp.js";
export {
  describeSessionChoice,
  getSessionDocumentLabel,
  getSessionDocumentSummary,
  isUnsavedWordDocument,
} from "./session-labels.js";
export {
  BRIDGE_PROTOCOL_VERSION,
  type BridgeApp,
  type BridgeClassifiedError,
  type BridgeError,
  type BridgeErrorClass,
  type BridgeEventMessage,
  type BridgeEventName,
  type BridgeEventPayloads,
  type BridgeHelloMessage,
  type BridgeHostInfo,
  type BridgeInvokeMessage,
  type BridgeInvokeMethod,
  type BridgeInvokeRequest,
  type BridgeResponseMessage,
  type BridgeRuntimeStateSlice,
  type BridgeSessionSnapshot,
  type BridgeStoredEvent,
  type BridgeToolDefinition,
  type BridgeToolExecutionResult,
  type BridgeTypedEvent,
  type BridgeVfsDeleteParams,
  type BridgeVfsEntry,
  type BridgeVfsListParams,
  type BridgeVfsReadParams,
  type BridgeVfsReadResult,
  type BridgeVfsWriteParams,
  type BridgeWelcomeMessage,
  type BridgeWireMessage,
  createBridgeEvent,
  createBridgeId,
  DEFAULT_BRIDGE_HOST,
  DEFAULT_BRIDGE_HTTP_URL,
  DEFAULT_BRIDGE_PORT,
  DEFAULT_BRIDGE_WS_PATH,
  DEFAULT_BRIDGE_WS_URL,
  DEFAULT_REQUEST_TIMEOUT_MS,
  extractToolError,
  extractToolImages,
  extractToolText,
  getDefaultRawExecutionTool,
  normalizeBridgeUrl,
  serializeForJson,
  toBridgeClassifiedError,
  toBridgeError,
  uint8ArrayToBase64,
} from "./protocol.js";
export {
  type WordToolContract,
  type WordToolGroup,
  getFirstClassWordToolContracts,
  getWordToolContract,
  WORD_TOOL_CONTRACTS,
  WORD_TOOL_CONTRACTS_BY_NAME,
} from "./word-tool-contracts.js";
